/**
 * Boshlang'ich ma'lumot: shaharlar, operatsiya katalogi va cold-start narxlari.
 * Narxlar — bozor tadqiqoti asosidagi TAXMINIY oraliq (so'mda), real bitim emas.
 */

export const CITIES = [
  { slug: 'tashkent', nameUz: 'Toshkent', nameRu: 'Ташкент' },
  { slug: 'samarkand', nameUz: 'Samarqand', nameRu: 'Самарканд' },
  { slug: 'bukhara', nameUz: 'Buxoro', nameRu: 'Бухара' },
  { slug: 'andijan', nameUz: 'Andijon', nameRu: 'Андижан' },
  { slug: 'fergana', nameUz: "Farg'ona", nameRu: 'Фергана' },
  { slug: 'namangan', nameUz: 'Namangan', nameRu: 'Наманган' },
  { slug: 'nukus', nameUz: 'Nukus', nameRu: 'Нукус' },
  { slug: 'qarshi', nameUz: 'Qarshi', nameRu: 'Карши' },
  { slug: 'urgench', nameUz: 'Urganch', nameRu: 'Ургенч' },
  { slug: 'navoiy', nameUz: 'Navoiy', nameRu: 'Навои' },
  { slug: 'jizzakh', nameUz: 'Jizzax', nameRu: 'Джизак' },
  { slug: 'termez', nameUz: 'Termiz', nameRu: 'Термез' },
];

export const CATEGORIES = [
  { slug: 'general-surgery', nameUz: 'Umumiy jarrohlik', nameRu: 'Общая хирургия', icon: 'scalpel' },
  { slug: 'urology', nameUz: 'Urologiya', nameRu: 'Урология', icon: 'kidney' },
  { slug: 'gynecology', nameUz: 'Ginekologiya', nameRu: 'Гинекология', icon: 'flower' },
  { slug: 'ophthalmology', nameUz: "Ko'z (oftalmologiya)", nameRu: 'Офтальмология', icon: 'eye' },
  { slug: 'orthopedics', nameUz: 'Ortopediya va travmatologiya', nameRu: 'Ортопедия', icon: 'bone' },
  { slug: 'ent', nameUz: 'LOR (quloq-burun-tomoq)', nameRu: 'ЛОР', icon: 'ear' },
  { slug: 'cardio', nameUz: 'Kardiologiya va tomirlar', nameRu: 'Кардиология и сосуды', icon: 'heart' },
  { slug: 'dentistry', nameUz: 'Stomatologiya', nameRu: 'Стоматология', icon: 'tooth' },
  { slug: 'plastic', nameUz: 'Plastik jarrohlik', nameRu: 'Пластическая хирургия', icon: 'sparkle' },
  { slug: 'proctology', nameUz: 'Proktologiya', nameRu: 'Проктология', icon: 'shield' },
];

interface SeedOperation {
  category: string;
  slug: string;
  nameUz: string;
  nameRu: string;
  aliasUz: string;
  aliasRu: string;
  descUz: string;
  descRu: string;
  keywords: string[];
  /** [min, p25, median, p75, max] — Toshkent uchun bazaviy taxminiy narx */
  price: [number, number, number, number, number];
}

const M = 1_000_000;

export const OPERATIONS: SeedOperation[] = [
  // ── Umumiy jarrohlik
  {
    category: 'general-surgery',
    slug: 'laparoscopic-cholecystectomy',
    nameUz: 'Laparoskopik xoletsistektomiya',
    nameRu: 'Лапароскопическая холецистэктомия',
    aliasUz: "O't pufagini olib tashlash (teshikchali usul)",
    aliasRu: 'Удаление желчного пузыря (лапароскопия)',
    descUz: "O't pufagidagi tosh sababli pufakni kichik teshiklar orqali olib tashlash. Odatda 1–3 kun yotoqda.",
    descRu: 'Удаление желчного пузыря при камнях через небольшие проколы. Обычно 1–3 дня в стационаре.',
    keywords: ["o't pufagi", "ot pufagi", 'tosh', 'safro', "o'ng biqin", "qovurg'a ostida og'riq", 'жёлчный', 'желчный пузырь', 'камни', 'холецистит', 'правый бок'],
    price: [8 * M, 11 * M, 14 * M, 18 * M, 25 * M],
  },
  {
    category: 'general-surgery',
    slug: 'appendectomy',
    nameUz: 'Appendektomiya',
    nameRu: 'Аппендэктомия',
    aliasUz: "Ko'richak (appenditsit) operatsiyasi",
    aliasRu: 'Операция по удалению аппендикса',
    descUz: "Yallig'langan ko'richakni olib tashlash. Ko'pincha shoshilinch bajariladi.",
    descRu: 'Удаление воспалённого аппендикса. Часто выполняется экстренно.',
    keywords: ['appenditsit', "ko'richak", 'korichak', "past o'ng qorin", 'appendiks', 'аппендицит', 'аппендикс', 'живот справа'],
    price: [5 * M, 7 * M, 9 * M, 12 * M, 16 * M],
  },
  {
    category: 'general-surgery',
    slug: 'inguinal-hernia-repair',
    nameUz: 'Chov churrasi operatsiyasi (gerniyaplastika)',
    nameRu: 'Пластика паховой грыжи',
    aliasUz: 'Chovdagi churra — to‘r (setka) qo‘yish',
    aliasRu: 'Паховая грыжа — установка сетки',
    descUz: 'Chov sohasidagi churrani tiklash, odatda maxsus to‘r (implant) bilan mustahkamlanadi.',
    descRu: 'Устранение паховой грыжи, обычно с укреплением сеткой.',
    keywords: ['churra', 'chov churrasi', 'gryja', 'do‘mboq', 'dumboq', 'грыжа', 'паховая грыжа', 'сетка'],
    price: [6 * M, 8 * M, 10 * M, 13 * M, 18 * M],
  },
  {
    category: 'general-surgery',
    slug: 'thyroidectomy',
    nameUz: 'Qalqonsimon bez operatsiyasi',
    nameRu: 'Операция на щитовидной железе',
    aliasUz: "Bo'qoq / qalqonsimon bez tugunini olib tashlash",
    aliasRu: 'Удаление узла щитовидной железы (зоб)',
    descUz: "Qalqonsimon bezdagi tugun yoki bo'qoqni qisman/to'liq olib tashlash.",
    descRu: 'Частичное или полное удаление узла либо зоба щитовидной железы.',
    keywords: ["bo'qoq", 'boqoq', 'qalqonsimon', 'shitovidka', 'tugun', 'зоб', 'щитовидка', 'узел'],
    price: [12 * M, 16 * M, 20 * M, 26 * M, 35 * M],
  },
  // ── Urologiya
  {
    category: 'urology',
    slug: 'kidney-stone-lithotripsy',
    nameUz: "Buyrak toshini maydalash (litotripsiya)",
    nameRu: 'Дробление камней почек (литотрипсия)',
    aliasUz: 'Buyrakdagi toshni jarrohliksiz maydalash',
    aliasRu: 'Дробление камня в почке без разреза',
    descUz: "Buyrak yoki siydik yo'lidagi toshni to'lqin bilan maydalash. Ko'pincha kesishsiz.",
    descRu: 'Дробление камня волной. Часто без разрезов.',
    keywords: ['buyrak toshi', 'buyrak', 'tosh', 'siydik', 'bel og‘riq', 'почка', 'камень в почке', 'литотрипсия'],
    price: [4 * M, 6 * M, 8 * M, 11 * M, 15 * M],
  },
  {
    category: 'urology',
    slug: 'turp-prostate',
    nameUz: 'Prostata adenomasi operatsiyasi (TURP)',
    nameRu: 'Операция аденомы простаты (ТУР)',
    aliasUz: 'Prostata kattalashishi — siydik yo‘li orqali operatsiya',
    aliasRu: 'Аденома простаты — трансуретральная операция',
    descUz: 'Kattalashgan prostata to‘qimasini siydik chiqarish yo‘li orqali olib tashlash.',
    descRu: 'Удаление разросшейся ткани простаты через уретру.',
    keywords: ['prostata', 'adenoma', 'siydik qiynalish', 'prostatit', 'простата', 'аденома', 'мочеиспускание'],
    price: [10 * M, 14 * M, 18 * M, 23 * M, 30 * M],
  },
  {
    category: 'urology',
    slug: 'varicocele',
    nameUz: 'Varikotsele operatsiyasi',
    nameRu: 'Операция варикоцеле',
    aliasUz: 'Moyakdagi tomirlar kengayishi',
    aliasRu: 'Расширение вен яичка',
    descUz: 'Moyak venalarining kengayishini bartaraf etish (ko‘pincha mikrojarrohlik).',
    descRu: 'Устранение расширения вен яичка, часто микрохирургически.',
    keywords: ['varikotsele', 'moyak', 'tomir', 'варикоцеле', 'яичко', 'вены'],
    price: [5 * M, 7 * M, 9 * M, 12 * M, 16 * M],
  },
  // ── Ginekologiya
  {
    category: 'gynecology',
    slug: 'laparoscopic-myomectomy',
    nameUz: 'Mioma olib tashlash (laparoskopik)',
    nameRu: 'Удаление миомы (лапароскопия)',
    aliasUz: "Bachadon miomasini teshikchali usulda olib tashlash",
    aliasRu: 'Удаление миомы матки через проколы',
    descUz: 'Bachadondagi mioma tugunini bachadonni saqlagan holda olib tashlash.',
    descRu: 'Удаление узла миомы с сохранением матки.',
    keywords: ['mioma', 'bachadon', 'ayollar', 'миома', 'матка'],
    price: [10 * M, 14 * M, 18 * M, 24 * M, 32 * M],
  },
  {
    category: 'gynecology',
    slug: 'ovarian-cyst-removal',
    nameUz: 'Tuxumdon kistasini olib tashlash',
    nameRu: 'Удаление кисты яичника',
    aliasUz: 'Kista operatsiyasi (laparoskopik)',
    aliasRu: 'Операция по удалению кисты',
    descUz: 'Tuxumdondagi kistani laparoskopik yo‘l bilan olib tashlash.',
    descRu: 'Лапароскопическое удаление кисты яичника.',
    keywords: ['kista', 'tuxumdon', 'киста', 'яичник'],
    price: [8 * M, 11 * M, 14 * M, 18 * M, 24 * M],
  },
  {
    category: 'gynecology',
    slug: 'hysterectomy',
    nameUz: 'Gisterektomiya (bachadonni olib tashlash)',
    nameRu: 'Гистерэктомия (удаление матки)',
    aliasUz: 'Bachadonni olib tashlash operatsiyasi',
    aliasRu: 'Операция удаления матки',
    descUz: 'Tibbiy ko‘rsatma bo‘yicha bachadonni to‘liq yoki qisman olib tashlash.',
    descRu: 'Полное или частичное удаление матки по показаниям.',
    keywords: ['bachadon', 'gisterektomiya', 'матка', 'гистерэктомия'],
    price: [12 * M, 16 * M, 21 * M, 27 * M, 36 * M],
  },
  // ── Oftalmologiya
  {
    category: 'ophthalmology',
    slug: 'cataract-phaco',
    nameUz: 'Katarakta operatsiyasi (fakoemulsifikatsiya + linza)',
    nameRu: 'Операция катаракты (факоэмульсификация + линза)',
    aliasUz: "Ko'zga parda tushishi — sun'iy linza qo'yish",
    aliasRu: 'Помутнение хрусталика — установка ИОЛ',
    descUz: "Xiralashgan gavharni olib, sun'iy linza qo'yish. Bir ko'z uchun narx.",
    descRu: 'Замена помутневшего хрусталика на искусственную линзу. Цена за один глаз.',
    keywords: ['katarakta', "ko'z", 'koz', 'parda', 'gavhar', 'xira', 'катаракта', 'глаз', 'хрусталик', 'линза'],
    price: [4 * M, 6 * M, 8 * M, 12 * M, 20 * M],
  },
  {
    category: 'ophthalmology',
    slug: 'lasik',
    nameUz: 'Lazer bilan ko‘rishni tiklash (LASIK)',
    nameRu: 'Лазерная коррекция зрения (LASIK)',
    aliasUz: 'Ko‘zoynakdan qutulish — lazer korreksiya',
    aliasRu: 'Избавление от очков — лазерная коррекция',
    descUz: 'Miopiya/gipermetropiya/astigmatizmni lazer bilan to‘g‘rilash. Ikki ko‘z uchun.',
    descRu: 'Лазерная коррекция близорукости/дальнозоркости/астигматизма. За оба глаза.',
    keywords: ['lasik', 'lazer', 'ko‘zoynak', 'miopiya', 'ko‘rish', 'лазик', 'зрение', 'близорукость', 'очки'],
    price: [5 * M, 7 * M, 9 * M, 13 * M, 18 * M],
  },
  // ── Ortopediya
  {
    category: 'orthopedics',
    slug: 'knee-arthroscopy',
    nameUz: 'Tizza artroskopiyasi (menisk)',
    nameRu: 'Артроскопия колена (мениск)',
    aliasUz: 'Tizzadagi menisk yirtilishi operatsiyasi',
    aliasRu: 'Операция при разрыве мениска',
    descUz: 'Tizza bo‘g‘imini kichik teshiklar orqali ko‘rib, meniskni tiklash yoki tozalash.',
    descRu: 'Артроскопическое восстановление или резекция мениска.',
    keywords: ['tizza', 'menisk', 'bo‘g‘im', 'artroskopiya', 'колено', 'мениск', 'сустав'],
    price: [8 * M, 11 * M, 14 * M, 18 * M, 25 * M],
  },
  {
    category: 'orthopedics',
    slug: 'hip-replacement',
    nameUz: 'Chanoq-son bo‘g‘imini almashtirish (endoprotez)',
    nameRu: 'Эндопротезирование тазобедренного сустава',
    aliasUz: 'Son bo‘g‘imiga protez qo‘yish',
    aliasRu: 'Замена тазобедренного сустава',
    descUz: 'Yemirilgan bo‘g‘imni sun’iy protez bilan almashtirish. Protez narxi alohida bo‘lishi mumkin.',
    descRu: 'Замена разрушенного сустава эндопротезом. Стоимость протеза может считаться отдельно.',
    keywords: ['endoprotez', 'son bo‘g‘imi', 'chanoq', 'protez', 'эндопротез', 'тазобедренный', 'сустав'],
    price: [30 * M, 40 * M, 52 * M, 68 * M, 90 * M],
  },
  {
    category: 'orthopedics',
    slug: 'spine-hernia',
    nameUz: 'Umurtqa churrasi operatsiyasi',
    nameRu: 'Операция грыжи позвоночника',
    aliasUz: 'Bel churrasi — mikrodiskektomiya',
    aliasRu: 'Грыжа диска — микродискэктомия',
    descUz: 'Umurtqalararo disk churrasini mikrojarrohlik yo‘li bilan olib tashlash.',
    descRu: 'Микрохирургическое удаление грыжи межпозвонкового диска.',
    keywords: ['umurtqa', 'bel og‘riq', 'churra', 'disk', 'oyoq uvishish', 'позвоночник', 'грыжа диска', 'поясница'],
    price: [15 * M, 20 * M, 26 * M, 34 * M, 48 * M],
  },
  // ── LOR
  {
    category: 'ent',
    slug: 'tonsillectomy',
    nameUz: 'Tonzillektomiya (bodomcha bezlarini olish)',
    nameRu: 'Тонзиллэктомия (удаление миндалин)',
    aliasUz: 'Angina — bodomchani olib tashlash',
    aliasRu: 'Хронический тонзиллит — удаление гланд',
    descUz: 'Surunkali yallig‘langan bodomcha bezlarini olib tashlash.',
    descRu: 'Удаление хронически воспалённых нёбных миндалин.',
    keywords: ['bodomcha', 'angina', 'tomoq', 'tonzillit', 'гланды', 'миндалины', 'ангина', 'горло'],
    price: [3 * M, 4.5 * M, 6 * M, 8 * M, 11 * M],
  },
  {
    category: 'ent',
    slug: 'septoplasty',
    nameUz: 'Septoplastika (burun to‘sig‘ini to‘g‘rilash)',
    nameRu: 'Септопластика (исправление перегородки носа)',
    aliasUz: 'Burun nafas olmasligi — to‘siqni to‘g‘rilash',
    aliasRu: 'Нос не дышит — выпрямление перегородки',
    descUz: 'Qiyshaygan burun to‘sig‘ini to‘g‘rilab, nafas olishni tiklash.',
    descRu: 'Выпрямление искривлённой перегородки для восстановления дыхания.',
    keywords: ['burun', 'to‘siq', 'nafas', 'septoplastika', 'нос', 'перегородка', 'дыхание'],
    price: [5 * M, 7 * M, 9 * M, 12 * M, 16 * M],
  },
  {
    category: 'ent',
    slug: 'sinusitis-surgery',
    nameUz: 'Gaymorit operatsiyasi (FESS)',
    nameRu: 'Операция при гайморите (FESS)',
    aliasUz: 'Burun bo‘shlig‘i yallig‘lanishi — endoskopik operatsiya',
    aliasRu: 'Эндоскопическая операция на пазухах',
    descUz: 'Burun yondosh bo‘shliqlarini endoskopik tozalash.',
    descRu: 'Эндоскопическая санация околоносовых пазух.',
    keywords: ['gaymorit', 'sinusit', 'burun', 'yiring', 'гайморит', 'синусит', 'пазухи'],
    price: [6 * M, 8 * M, 10 * M, 13 * M, 18 * M],
  },
  // ── Kardio / tomir
  {
    category: 'cardio',
    slug: 'coronary-stenting',
    nameUz: 'Koronar stentlash',
    nameRu: 'Коронарное стентирование',
    aliasUz: 'Yurak tomiriga stent qo‘yish',
    aliasRu: 'Установка стента в сосуд сердца',
    descUz: 'Torayagan yurak tomirini stent bilan kengaytirish. Stent narxi alohida hisoblanishi mumkin.',
    descRu: 'Расширение суженной коронарной артерии стентом. Стент может считаться отдельно.',
    keywords: ['stent', 'yurak', 'tomir', 'infarkt', 'koronar', 'стент', 'сердце', 'сосуд', 'инфаркт'],
    price: [25 * M, 32 * M, 40 * M, 52 * M, 70 * M],
  },
  {
    category: 'cardio',
    slug: 'varicose-veins',
    nameUz: 'Varikoz (oyoq venalari) operatsiyasi',
    nameRu: 'Операция варикоза вен ног',
    aliasUz: 'Oyoqdagi ko‘kargan tomirlar — lazer bilan',
    aliasRu: 'Вены на ногах — лазерная облитерация',
    descUz: 'Kengaygan yuza venalarni lazer yoki klassik usulda bartaraf etish.',
    descRu: 'Устранение расширенных поверхностных вен лазером или классически.',
    keywords: ['varikoz', 'oyoq', 'tomir', 'vena', 'shish', 'варикоз', 'вены', 'ноги'],
    price: [4 * M, 6 * M, 8 * M, 11 * M, 15 * M],
  },
  // ── Stomatologiya
  {
    category: 'dentistry',
    slug: 'dental-implant',
    nameUz: 'Tish implanti (bitta tish)',
    nameRu: 'Дентальный имплант (один зуб)',
    aliasUz: 'Tushgan tish o‘rniga implant qo‘yish',
    aliasRu: 'Установка импланта на место зуба',
    descUz: 'Bitta tish o‘rniga implant + abatment + koronka. Narx bosqichma-bosqich bo‘lishi mumkin.',
    descRu: 'Имплант + абатмент + коронка на один зуб. Оплата может быть поэтапной.',
    keywords: ['implant', 'tish', 'koronka', 'имплант', 'зуб', 'коронка'],
    price: [3 * M, 4.5 * M, 6 * M, 8.5 * M, 13 * M],
  },
  {
    category: 'dentistry',
    slug: 'wisdom-tooth-removal',
    nameUz: 'Aql tishini olib tashlash (murakkab)',
    nameRu: 'Удаление зуба мудрости (сложное)',
    aliasUz: 'Chiqmagan aql tishi operatsiyasi',
    aliasRu: 'Операция при ретинированном зубе мудрости',
    descUz: 'Suyak ichida qolgan yoki qiyshiq aql tishini jarrohlik yo‘li bilan olish.',
    descRu: 'Хирургическое удаление ретинированного или дистопированного зуба.',
    keywords: ['aql tishi', 'tish', 'olish', 'зуб мудрости', 'удаление зуба'],
    price: [0.6 * M, 1 * M, 1.5 * M, 2.2 * M, 3.5 * M],
  },
  // ── Plastik
  {
    category: 'plastic',
    slug: 'rhinoplasty',
    nameUz: 'Rinoplastika (burun shaklini o‘zgartirish)',
    nameRu: 'Ринопластика',
    aliasUz: 'Burun estetik operatsiyasi',
    aliasRu: 'Эстетическая операция носа',
    descUz: 'Burunning shakli va nafas funksiyasini estetik/funksional tuzatish.',
    descRu: 'Коррекция формы и функции носа.',
    keywords: ['rinoplastika', 'burun', 'estetik', 'ринопластика', 'нос'],
    price: [12 * M, 16 * M, 21 * M, 28 * M, 40 * M],
  },
  {
    category: 'plastic',
    slug: 'abdominoplasty',
    nameUz: 'Abdominoplastika (qorin plastikasi)',
    nameRu: 'Абдоминопластика',
    aliasUz: 'Qorindagi ortiqcha teri va yog‘ni olish',
    aliasRu: 'Удаление лишней кожи и жира на животе',
    descUz: 'Qorin devorini tortish va ortiqcha teri-yog‘ni olib tashlash.',
    descRu: 'Подтяжка передней брюшной стенки с удалением избытков.',
    keywords: ['qorin', 'plastika', 'yog‘', 'teri', 'живот', 'абдоминопластика'],
    price: [15 * M, 20 * M, 26 * M, 34 * M, 45 * M],
  },
  // ── Proktologiya
  {
    category: 'proctology',
    slug: 'hemorrhoidectomy',
    nameUz: 'Gemorroy operatsiyasi',
    nameRu: 'Операция геморроя',
    aliasUz: 'Bavosil — jarrohlik yoki lazer',
    aliasRu: 'Геморрой — хирургия или лазер',
    descUz: 'Gemorroidal tugunlarni klassik, lazer yoki Longo usulida davolash.',
    descRu: 'Лечение геморроидальных узлов классически, лазером или методом Лонго.',
    keywords: ['gemorroy', 'bavosil', 'qon', 'геморрой', 'узлы'],
    price: [4 * M, 6 * M, 8 * M, 11 * M, 15 * M],
  },
  {
    category: 'proctology',
    slug: 'anal-fissure',
    nameUz: 'Anal yoriq (fissura) operatsiyasi',
    nameRu: 'Операция анальной трещины',
    aliasUz: 'Surunkali yoriqni davolash',
    aliasRu: 'Лечение хронической трещины',
    descUz: 'Surunkali anal yoriqni jarrohlik yo‘li bilan davolash.',
    descRu: 'Хирургическое лечение хронической анальной трещины.',
    keywords: ['yoriq', 'fissura', 'og‘riq', 'трещина', 'анальная'],
    price: [3 * M, 4 * M, 5.5 * M, 7 * M, 10 * M],
  },
];

/** Shahar bo'yicha narx koeffitsienti — poytaxtda qimmatroq. */
export const CITY_PRICE_FACTOR: Record<string, number> = {
  tashkent: 1.0,
  samarkand: 0.86,
  bukhara: 0.84,
  andijan: 0.8,
  fergana: 0.8,
  namangan: 0.78,
  nukus: 0.74,
  qarshi: 0.78,
  urgench: 0.76,
  navoiy: 0.82,
  jizzakh: 0.76,
  termez: 0.75,
};

export const DEMO_CLINICS = [
  { name: 'Medion Klinikasi', city: 'tashkent', plan: 'pro', rating: 4.8, deals: 142, about: '15 yillik tajriba, xalqaro sertifikatlangan jarrohlar. Laparoskopiya markazi.' },
  { name: 'Akfa Medline', city: 'tashkent', plan: 'pro', rating: 4.7, deals: 210, about: 'Zamonaviy multidisiplinar shifoxona, 24/7 shoshilinch yordam.' },
  { name: 'Shox Med Servis', city: 'tashkent', plan: 'basic', rating: 4.4, deals: 63, about: 'Umumiy jarrohlik va urologiya bo‘yicha ixtisoslashgan klinika.' },
  { name: 'Intermed Innovation', city: 'tashkent', plan: 'basic', rating: 4.5, deals: 88, about: 'Ko‘z va LOR yo‘nalishida kuchli jamoa.' },
  { name: 'Samarqand Medical Center', city: 'samarkand', plan: 'pro', rating: 4.6, deals: 74, about: 'Viloyatdagi eng yirik xususiy jarrohlik markazi.' },
  { name: 'Buxoro KlinikaTop Plus', city: 'bukhara', plan: 'basic', rating: 4.3, deals: 41, about: 'Ortopediya va travmatologiya bo‘yicha tajribali jamoa.' },
  { name: 'Andijon Zamon Klinika', city: 'andijan', plan: 'basic', rating: 4.2, deals: 35, about: 'Hamyonbop narxlar, kunduzgi statsionar.' },
  { name: 'Farg‘ona Med Life', city: 'fergana', plan: 'pro', rating: 4.5, deals: 57, about: 'Ginekologiya va laparoskopiya markazi.' },
];

export const OFFER_INCLUDE_PRESETS = [
  'Operatsiya',
  'Narkoz (anesteziya)',
  'Palata (2 kun)',
  'Dori-darmon',
  'Operatsiyadan oldingi tekshiruv',
  'Jarroh nazorati (1 oy)',
  'Bandaj / sarflanuvchi materiallar',
];

export const OFFER_ADVANTAGE_PRESETS = [
  'Oliy toifali jarroh',
  'Yangi avlod jihozlari',
  'Xalqaro sertifikat',
  '24/7 nazorat',
  'Bepul konsultatsiya',
  'Bo‘lib to‘lash imkoni',
];
